### PR TITLE
Restore pre-1.1.0 behavior of the block argument

### PR DESCRIPTION
**Pull request by mshibuya**
Here's my proposal on fixing the issue #56.

### CODE REVIEW

**Comment by nachiket87** [comment]
Please can this be reviewed soon ! thanks <3

**Comment by mshibuya** [comment]
@arkadiyt Is there any chance you could review this PR?
As the time passes the situation gets worse, because people start implement their code based on the broken new API.

**Comment by edwinhorneij** [comment]
@arkadiyt could you please review this PR?

**Comment by arkadiyt** [comment]
Closing as per https://github.com/arkadiyt/ssrf_filter/issues/56#issuecomment-1703190798

**Pull request closed without merging**
